name: Create and Export Recipe

on:
  workflow_dispatch:
  push:
    paths:
      - '*.xml.*'
      - '*.sig'
      - 'conanfile.py'
      - '.github/workflows/conan-package.yml'
    branches:
      - main
      - '[0-9].[0-9]*'

jobs:
  conan-package:
    uses: lulzbot3d/CuraLE_Workflows/.github/workflows/conan-package.yml@main
    with:
      platform_windows: false
      platform_mac: false
      install_system_dependencies: false
    secrets: inherit